export const Utils = [
  {
    Img: "/list.png",
    Head: "Order Acceptance",
    Percent: "85%",
    Gimg: "/down.png",
    value: "8%",
    btnTxt: "Phase 1 Goal",
    class: "red",
    btnClass: "order",
  },
  {
    Img: "/time.png",
    Head: "Reaching Vendor",
    Percent: "95%",
    Gimg: "/up.png",
    value: "8%",
    btnTxt: "Phase 2 Goal",
    class: "green",
    btnClass: "Vendor",
  },
  {
    Img: "/product.png",
    Head: "Delivery Order",
    Percent: "99%",
    Gimg: "/up.png",
    value: "8%",
    btnTxt: "Ultimate Goal",
    class: "green",
    btnClass: "delivery",
    mar: "margin_no",
  },
  {
    Img: "/dollar.png",
    Head: "Clearing Payments",
    Percent: "65%",
    Gimg: "/down.png",
    value: "8%",
    btnTxt: "None",
    class: "red",
    btnClass: "pay",
  },
  {
    Img: "/ribbon.png",
    Head: "Total Quality Score",
    Percent: "85%",
    Gimg: "/down.png",
    value: "8%",
    btnTxt: "Phase 1 Goal",
    class: "red",
    btnClass: "score",
  },
];
